---

- name: Bash directory
  file:
    path: /etc/bash_completion.d
    state: directory
    recurse: yes
  when: conf.shell == "bash"


- name: Bash
  become: true
  become_method: sudo
  shell: /home/vagrant/.cargo/bin/rustup completions bash > /etc/bash_completion.d/rustup.bash-completion
  args:
    creates: /etc/bash_completion.d/rustup.bash-completion
  when: conf.shell == "bash"

- name: Fish directory
  file:
    path: /home/vagrant/.config/fish/completions
    state: directory
    recurse: yes
  when: conf.shell == "fish"

- name: Fish
  shell: /home/vagrant/.cargo/bin/rustup completions fish > /home/vagrant/.config/fish/completions/rustup.fish
  args:
    creates: /home/vagrant/.config/fish/completions/rustup.fish
  when: conf.shell == "fish"

- name: Zsh directory
  file:
    path: /home/vagrant/.zfunc
    state: directory
    recurse: yes
  when: conf.shell == "zsh"

- name: Zsh
  shell: /home/vagrant/.cargo/bin/rustup completions zsh > /home/vagrant/.zfunc/_rustup
  args:
    creates: /home/vagrant/.zfunc/_rustup
  when: conf.shell == "zsh"
